---
jobs:
- name: build
  plan:
  - get: source
    params: {depth: 1}
    trigger: true
  - put: docker-image
    params:
      build: source
      tag: source/.git/ref

- name: test
  plan:
  - get: source
    params: {depth: 1}
    passed: [build]
    trigger: true
  - get: docker-image
    passed: [build]
    params:
      save: true
  - get: postgres
    params:
      save: true
  - task: run-tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
      - name: source
      - name: docker-image
      - name: postgres
      run:
        path: sh
        args:
        - -ec
        - |
          source /docker-lib.sh
          start_docker
          # preload images
          docker load -i docker-image/image
          docker tag "$(cat docker-image/image-id)" "app"
          docker load -i postgres/image
          docker tag "$(cat postgres/image-id)" "db"
          # run tests
          docker-compose -f source/docker-compose.test.yml up --abort-on-container-exit
          # clean up
          docker-compose -f source/docker-compose.test.yml down
          docker volume rm $(docker volume ls -q)

- name: deploy
  plan:
  - get: docker-image
    passed: [build, test]
    trigger: true
  - get: helm-values
  - put: helm-release
    params:
      chart: mojanalytics/cpanel
      values:
      - helm-values/chart-env-config/dev/cpanel.yml
      override_values:
      - { key: API.Image.Tag, path: docker-image/tag }
      - { key: API.Branch, value: master }
      - { key: tags.branch, value: false }

resources:
- name: source
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-control-panel.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    repository: quay.io/mojanalytics/control-panel
    username: ((quay.username))
    password: ((quay.password))

- name: postgres
  type: docker-image
  source:
    repository: postgres
    tag: 9.6.2

- name: helm-values
  type: git
  source:
    git_crypt_key: ((gitcryptKeys.config))
    uri: https://github.com/ministryofjustice/analytics-platform-config.git

- name: helm-release
  type: helm
  source:
    cluster_url: ((kubernetes.apiUrl))
    cluster_ca: ((kubernetes.caCert))
    helm_host: tiller-deploy.kube-system:44134
    token: ((kubernetes.token))
    namespace: default
    release: cpanel-master
    repos:
    - name: mojanalytics
      url: http://moj-analytics-helm-repo.s3-website-eu-west-1.amazonaws.com

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.9.1
